### ISSUE TITLE
The asks of roles is done without the "effective" URI parms

### ISSUE THREAD

**Issue by jcalderin** [telefonicaid/fiware-orion-pep#147]
When PEP ask for roles of a user, use the url in the configuration, and adds as a URI parm the user.id of the user who owns the roles.

If the role is assignment directly, its works fine, but if the role is inherit, the keystone not respond with this roles, unless `&effective` URI parm is added, then, PEP never sent this roles to Keypass(AccessControl) and respond with an error

**Comment by fgalan** [comment]
This bugfix is needed for IoTP v1.1 ?

**Comment by mrutid** [comment]
Yes it is.
