### ISSUE TITLE
When json is specefied in content-type but the content is not a json, the error is not captureed

### ISSUE THREAD

**Issue by jcalderin** [telefonicaid/fiware-orion-pep#194]
When the content-type is set to `application/json;charset utf-8`  but is sent as peylaod 
```
<xml>   >       
```
The error expected is a 400 with the name `WRONG_JSON_PAYLOAD` but the next error is received:
```
Code: 403

{
    "message": "invalid json",
    "name": "Error"
}
```

**Comment by fgalan** [comment]
Fixed in PR #200
