### ISSUE TITLE
Logs format has to content "component"

### ISSUE THREAD

**Issue by jcalderin** [telefonicaid/fiware-orion-pep#195]
This is what PEP returns:
```
time=2015-03-10T17:09:08.662Z | lvl=DEBUG | corr=870da9a9-9b85-4bb1-96e9-b1ff8027e93b | trans=870da9a9-9b85-4bb1-96e9-b1ff8027e93b | op=/ | msg=response-time: 6 statusCode: 403
```

This is what its expected:
```
time=2015-03-10T17:09:08.662Z | lvl=DEBUG | Component="PEP*| corr=870da9a9-9b85-4bb1-96e9-b1ff8027e93b | trans=870da9a9-9b85-4bb1-96e9-b1ff8027e93b | op=/ | msg=response-time: 6 statusCode: 403
``

**Comment by jcalderin** [comment]
Ask for the format to RELs

**Comment by fgalan** [comment]
I think component is optional. E.g. in Orion Context Broker we discussed this with REL and it was decided to not use it:

```
time=2015-03-12T12:32:44.527CET | lvl=INFO | trans=1425057766-510-00003325613 | function=sendHttpSocket | comp=Orion | msg=clientSocketHttp.cpp[375]: Transaction ended
 ```

In that case, this issue wouldn't be a bug and it could even be closed if we don't find any useful use for component field in the case of PEP.

**Comment by dmoranj** [comment]
This same issue would affect CEP as well, as both use the same log format. This log format, by the way, is the one used in TDAF's official Node.js log library, so more components in the company are using this exact same format. My vote is to keep it as it is (the component can be guessed by the filename in the logging tools).

**Comment by dmoranj** [comment]
Decided to close it offline, without further action.

NTC
