### ISSUE TITLE
When the AC and HEaders are disabled, not send x-auth-token raise a non capture error

### ISSUE THREAD

**Issue by jcalderin** [telefonicaid/fiware-orion-pep#197]
When the pep is configured to not use AC and do not check headers, and a request is sent without the header "x-auth-token" the error expected is "MISSING-HEADERS" but pep returns:

```
{
    "message": "Cannot read property 'length' of undefined",
    "name": "TypeError"
}
```

**Comment by dmoranj** [comment]
Fixed in #198
