### ISSUE TITLE
Protect access to the STH component using PEP

### ISSUE THREAD

**Issue by gtorodelvalle** [telefonicaid/fiware-orion-pep#206]
Access to the STH component (https://github.com/telefonicaid/IoT-STH) has to be secured and protected using PEP.

**Comment by fgalan** [comment]
I think that PEP already include functionality to secure STH API using existing plugins (we include this task in past month sprint and it was resolved without touching the code), but let's wait for @dmoranj for telling about this.

**Comment by dmoranj** [comment]
As Fermin sais, that functionality is already in the external generic PEP proxy, so no work should be done here. Even in the case of special needs for the STH the appropriate course of action would be to contribute a plugin to the PEP proxy, not to codify one again.

**Comment by dmoranj** [comment]
Spoke about it offline. It seems the Rest plugin may do.
