### ISSUE TITLE
Improve log performance avoiding expensive operations

### ISSUE THREAD

**Issue by espencer** [telefonicaid/fiware-orion-pep#48]
Debug log should avoid to perform potentially expensive operations. Take the following example

```js
logger.debug('Keystone response retrieving roles:\n\n %s', JSON.stringify(body, null, 4));
```

In this example, `JSON.stringgify` is executed, even if the log level is not `debug`.

Effort: 2 man day

**Comment by fgalan** [comment]
Implemented in PR #203
